export function analizePhoto(photoUri) {
    
    //codice relativo all'analisi dell'immagine mancante. simulo l'analisi con la funzione mockAnalysis
    let result = mockAnalysis()
    return result
}

const mockAnalysis = () => {
    let i = Math.floor(Math.random() * 9)
    return diseases[i]
}

const diseases = [
    {name: 'Tutto a posto!', description: 'Durante l\'analisi non è stato riscontrato alcun problema.', gravity: 0},
    {name: 'Carie dentale', description:'La carie dentale è il principale risultato di un processo di demineralizzazione dei denti, nonché una delle infezioni del cavo orale in assoluto più diffuse. La malattia cariosa è considerata come una delle cause principali della caduta dei denti nei bambini con meno di 12 anni, come indicato dal Ministero della Salute, ed è determinata prevalentemente dal batterio Streptococcus mutans.',gravity:1},
    {name: 'Gengivite', description:'La gengivite, termine medico utilizzato per indicare il primo stadio della malattia parodontale, è causata dall’accumulo di batteri nei solchi gengivali (lungo il margine gengivale e nella parte sottostante) e dalla conseguente produzione di tossine. Le gengive reagiscono alla presenza di tali tossine con stati infiammatori e tumefazioni che, a loro volta, sono all’origine dei sanguinamenti che si verificano durante lo spazzolamento.',gravity:1},
    {name: 'Malattia parodontale', description:'La gengivite, infiammazione che si estende sotto il margine gengivale e interessa le strutture ossee e i tessuti che circondano e supportano i denti, può determinare l’insorgenza di malattie parodontali. La formazione di tasche intorno ai denti può causare stati di infiammazione e riassorbimenti ossei, nonché la caduta dei denti stessi a causa della distruzione dell’osso.',gravity:2},
    {name: 'Malattia mani-bocca-piedi', description:'La malattia mani-bocca-piedi è una infezione che i bambini in età scolare e prescolare possono contrarre con grande facilità. Stando a quanto riportato dall’Ospedale Pediatrico Bambino Gesù, uno dei virus più frequentemente in causa è il Coxsackie A16. Dopo uno o due giorni di mal di gola e febbre, piccole vescicole dolorose possono comparire nel cavo orale, sul palmo delle mani, sulla pianta dei piedi e sui glutei. Fortunatamente, l’eruzione scompare nel giro di tre giorni.',gravity:1},
    {name: 'Herpangina', description:'L’herpangina, anche chiamata erpangina o faringite vescicolare, è un’infezione legata alla malattia mani-bocca-piedi che colpisce i bambini di età compresa tra 3 e 10 anni e si manifesta prevalentemente durante i periodi estivo e autunnale. Febbre, mal di gola e difficoltà alla deglutizione sono i primi sintomi dell’infezione, seguiti dalla comparsa di piccole vescicole nella parte posteriore della cavità orale che tendono all’ulcerazione in caso di rottura. L’herpangina guarisce solitamente nel giro di tre-cinque giorni.',gravity:1},
    {name: 'Mughetto', description:'L’eccessiva proliferazione della Candida albicans, fungo naturalmente presente nell’organismo umano, può determinare l’insorgenza del mughetto. Tra le cause scatenanti, possono rientrare anche terapie mediche quali le cure antibiotiche, la chemioterapia o altre terapie radianti. La malattia è caratterizzata dalla comparsa di placche biancastre e lattescenti sulla lingua, all’interno delle guance, sul palato e nella parte posteriore della bocca. Il mughetto è una delle infezioni più diffuse tra i pazienti affetti da HIV.',gravity:2},
    {name: 'Afte', description:'Le afte sono piccole lesioni che si formano sulle gengive o su altri tessuti della mucosa orale. I dentisti le chiamano stomatiti aftose o ulcere aftose. Sono particolarmente diffuse tra i bambini e gli adolescenti, ma l’origine e il meccanismo che portano alla loro comparsa non sono del tutto noti. Tra le possibili cause scatenanti, lo stress, gli sbalzi ormonali, i disturbi immunitari, l’ipersensibilità verso alcuni alimenti e le infezioni che possono derivarne. Le lesioni tendono solitamente a guarire nel giro di 10-14 giorni.',gravity:1},
    {name: 'Herpes labiale', description:'L’herpes labiale è un’infezione causata dall’Herpes Simplex Virus e secondo le stime fornite dall’Organizzazione Mondiale della Salute (OMS) è un problema che riguarderebbe 3,7 miliardi di persone al mondo sotto i 50 anni. Alla prima insorgenza, la malattia può esordire con sintomi simil-influenzali, vescicole e ulcere sulle gengive e sulla lingua, ma potrebbe anche avere un decorso completamente asintomatico. Dopo l’infezione, il virus resta nell’organismo in modo permanente, ma con le dovute precauzioni potrebbe rimanere latente. Le recidive sono solitamente meno acute e si risolvono nel giro di una settimana o 10 giorni al massimo. Vescicole piene di liquido tendono a comparire intorno alla bocca e dopo uno o due giorni, si rompono dando luogo alla formazione di croste, senza causare altri fastidi. I bambini di età compresa tra uno e tre anni, portatori del virus simplex, potrebbero talvolta sviluppare una stomatite erpetica o gengivostomatite, patologia che si manifesta con la tumefazione delle gengive e la comparsa di vescicole isolate. I bambini possono presentare febbre, essere più irritabili e stancarsi più facilmente. Nei giorni successivi, i sintomi precedentemente descritti compaiono sulle gengive, mentre la bocca si copre solitamente di piccole ulcere. Alla scomparsa dei sintomi, il virus rimane quiescente nell’organismo, ma può riattivarsi in caso di stress, situazioni traumatiche ed eccessive esposizioni ai raggi solari e al freddo. Spazzolare i denti due o tre volte al giorno con un dentifricio al fluoro e usare filo interdentale o scovolino dentale una volta al giorno consentono di prevenire la formazione della carie e l’insorgenza di disturbi gengivali o di altre malattie parodontali. Grazie a una corretta igiene orale, dentisti, igienisti dentali e medici potranno contribuire più facilmente alla cura di altre infezioni orali.',gravity:2},
]

//fonte: https://www.colgate.it/oral-health/mouth-sores-and-infections/eight-common-oral-infections-0615